### ISSUE TITLE
link to add bot does not work

### ISSUE THREAD

**Issue by Meiscool125** [Layendan/discord_clip#9]
link "https://www.caughtin48khz.tech/" gives error "www.caughtin48khz.tech’s DNS address could not be found. Diagnosing the problem."

**Comment by Layendan** [comment]
Hi! Yeah we had a year of free domain name through one of our hackathon sponsors which ran out a while ago. The bot also isn't hosted anymore since the credits we had for the hosting service also ran out.

I forgot to archive this repository. The code should still work if you're interested in hosting the bot yourself. Although discord's new clip feature practically does the same thing.
